name: HRM Attendance

on:
  schedule:
    # 0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday
    # We list 0,1,2,3,5,6 to skip 4 (Thursday)
    
    # 9:00 AM BD Time (03:00 UTC) - Excludes Thursday
    - cron: '0 3 * * 0,1,2,3,5,6'
    
    # 6:00 PM BD Time (12:00 UTC) - Excludes Thursday
    - cron: '0 12 * * 0,1,2,3,5,6'
  
  # Allows you to run it manually to test
  workflow_dispatch:

jobs:
  run-script:
    # IMPORTANT: Keep this as 'self-hosted' so it runs on your laptop 
    # and bypasses the 404 Geo-Block error.
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Attendance Script
        env:
          HRM_EMAIL: ${{ secrets.HRM_EMAIL }}
          HRM_PASSWORD: ${{ secrets.HRM_PASSWORD }}
        run: python attendance.py
