name: HRM Attendance

on:
  schedule:
    # 0=Sun, 1=Mon, 2=Tue, 3=Wed, 4=Thu, 5=Fri, 6=Sat
    # We use 0,1,2,3,5,6 to run every day EXCEPT Thursday (4)
    
    # 9:00 AM BD Time (03:00 UTC)
    - cron: '0 3 * * 0,1,2,3,5,6'
    
    # 6:00 PM BD Time (12:00 UTC)
    - cron: '0 12 * * 0,1,2,3,5,6'
  
  # Allows manual testing button
  workflow_dispatch:

jobs:
  run-script:
    # "ubuntu-latest" runs on GitHub Cloud (Free, 24/7, No PC needed)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run Attendance Script
        env:
          HRM_EMAIL: ${{ secrets.HRM_EMAIL }}
          HRM_PASSWORD: ${{ secrets.HRM_PASSWORD }}
        run: python attendance.py
